# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 05:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default=datetime.datetime(2019, 6, 13, 5, 16, 13, 283407, tzinfo=utc), upload_to='articles/'),
            preserve_default=False,
        ),
    ]
